### ISSUE TITLE
Jasmine fixtures only working in rake or browser, not both

### ISSUE THREAD

**Issue by aduggin** [guidance-guarantee-programme/pension_guidance#176]
We've added jasmine to the 'ga-link-tracking' branch and are running fixtures with the 'jasmine-jquery-rails' gem.

To get fixtures to work we need to set the fixturePath in the following file:
https://github.com/guidance-guarantee-programme/pension_guidance/blob/ga-link-tracking/spec/javascripts/click-trackerSpec.js

To get fixtures to work in rake (rake spec:javascript) the path needs to be set to:
jasmine.getFixtures().fixturesPath='../../spec/javascripts/fixtures'

To get fixtures to work in the browser (http://localhost:3000/specs) the path needs to be set to:
jasmine.getFixtures().fixturesPath = '/assets/fixtures/';

It's currently set up to work in rake so that the tests can be run in CI, but if someone tries to run it in a browser it will fail - which will be confusing. Is there a way to get this working in both?

**Comment by gjvis** [comment]
Resolved by #179
