### ISSUE TITLE
Cache/memoize locations

### ISSUE THREAD

**Issue by stevenwilkin** [guidance-guarantee-programme/pension_guidance#251]
Every time we query the locations repository [the locations repository is instantiated](https://github.com/guidance-guarantee-programme/pension_guidance/blob/d661d49330f613a4e1cfe26ca9909505f675db58/lib/locations.rb#L7) and every time the locations repository is instantiated [the GeoJSON is pulled down](https://github.com/guidance-guarantee-programme/pension_guidance/blob/582db7744d7004d5e4e0838818cdccafb9b2dcde/lib/locations/repository.rb#L4).

This should be fine for MVP but we should look into caching the GeoJSON and/or memoizing the repository.

**Comment by gjvis** [comment]
Cache for a configurable amount of time I reckon

**Comment by stevenwilkin** [comment]
GeoJSON fetches are now cached with #258
