### ISSUE TITLE
Prefixing "Citizens Advice" to all delivery locations

### ISSUE THREAD

**Issue by stevenwilkin** [guidance-guarantee-programme/pension_guidance#337]
The new outreach locations aren't in CABs:

![image](https://cloud.githubusercontent.com/assets/45121/10342627/d7bd05c8-6d11-11e5-928f-4056b9e1eccb.png)

We currently have nothing to distinguish between CABs and outreaches so this sentence will need to be reworded I think, it'll not be enough to just remove "Citizens Advice".

Here's the appropriate line [in the view](https://github.com/guidance-guarantee-programme/pension_guidance/blob/4db29b44e0f76a31fbb19d07af9dda26a7959fc2/app/views/locations/show.html.erb#L26).

**Comment by andrewgarner** [comment]
I've spoken with @mcornford. We're going to monitor this for the time being.
